### ISSUE TITLE
Usage within NextJS

### ISSUE THREAD

**Issue by NotAJeetDev** [spectrexyz/use-nft#178]
Attempting to use this module with NextJS results in the following message being displayed.

`
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/naj/code/project/node_modules/use-nft/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
`

This happens both when using it with the useNFT hook and using FetchWrapper
This is using NextJS 12.1.5 with React 18.1.0

**Comment by bpierre** [comment]
The issue was related to the way Next.js handles the CJS and ESM exports of a library. I decided to remove the CJS export as it should now be supported in Node and make things simpler.

A Next.js example has also been added: https://github.com/spectrexyz/use-nft/tree/744e4c374edc45261b8aa9f174fd1cecac2152a6/examples/nextjs

**Comment by NotAJeetDev** [comment]
Hey, 

Sorry I'm AFK for a little while, I shall check this when I get back in a couple of days. I used a previous version with success, but shall update to the latest. Thank you for the swift fix though!

**Comment by NotAJeetDev** [comment]
Hey, that worked great and I can confirm it's all resolved :)
Thank you!
